### ISSUE TITLE
Remove .gitignore

### ISSUE THREAD

**Issue by mbarinov** [bobrik/pupergrep#3]
In root folder of your project exist a .gitignore file whitch ignore Idea files. This functionallity must be set up in global gitignore, not in project. Please remove this file. 

[Article](http://jqr.github.com/2009/02/03/global-git-ignore.html) about global gitignore

**Comment by nickynick** [comment]
What if someone doesn't have this in his global .gitignore? He must add it prior to contributing? This makes no sense.
