### ISSUE TITLE
Make block with controls on left side always visible

### ISSUE THREAD

**Issue by f0y** [bobrik/pupergrep#5]
I have to constantly scroll up and down to change filters and do other actions because the latest logs appears on the bottom but the block with controls appears on the top. I think the visiblity of the block should be independent of the log position. 
It will greatly improve usablity, I hope =)

**Comment by bobrik** [comment]
The plan is to make right block just like terminal window where new line is always at the bottom of the visible screen, probably with scrollbars. This will actually make left side always visible.

Closing for now
