### ISSUE TITLE
Is it possible to point log on the another machine?

### ISSUE THREAD

**Issue by hennadii-demchenko** [bobrik/pupergrep#6]
The tool is great, but i wonder how can I use it to tail logs not only from current machine?
Is it possible to point to the remote file through ssh?

**Comment by bobrik** [comment]
You may use `scribe` or `syslog` for this, but for simple usage you may run in `screen` something like this:

```
while true; do ssh user@host -- tail -F /path/to/remote/log >> /path/to/local/log; done
```

and add /path/to/local/log to your pupergrep.

**Comment by hennadii-demchenko** [comment]
thank you
