### ISSUE TITLE
Nginx proxying trouble

### ISSUE THREAD

**Issue by aidgab** [bobrik/pupergrep#7]
Couldn't find how to make nginx work with it.
When connecting node.js server shows  records like "handshake authorized Ifpj6-OWYAD4Z6Zrfk0N"
But after a long delay "transport end (close timeout)"

Nginx's log is full of "18:43:08 [error] 27804#0: *6 upstream timed out (110: Connection timed out) while reading response header from upstream ....."

**Comment by bobrik** [comment]
What nginx version do you use? Do you use nginx config from readme?

**Comment by rlidwka** [comment]
I would suggest this:
https://github.com/rlidwka/pupergrep/commit/b366f78c274caaaac04b2840c7514773a6abcb46

until nginx won't officially support websockets. That's far better than downgrading to xhr-polling for my taste.

**Comment by aidgab** [comment]
Yes, I do use config from readme. Nginx ver 0.7.67. Upper solution from  @rlidwka helped. Thank you!
But it doesn't work if I bind puperlog to 127.0.0.1, not public ip. So, if I bind pupergrep to 127.0.0.1 and proxy from nginx to it, it doesn't work.
I'll try upgrading nginx, but it's rather weird.

**Comment by bobrik** [comment]
Try at leas nginx-1.0.14, i haven't tried lower versions.

Closing issue for now.

**Comment by aidgab** [comment]
Right. Finally I upgraded nginx to 1.2.3 and got a result using config from readme. Sorry for inconvenience.

**Comment by rlidwka** [comment]
> But it doesn't work if I bind puperlog to 127.0.0.1, not public ip. So, if I bind pupergrep to 127.0.0.1 and proxy from nginx to it, it doesn't work.

You can bind puperlog to public IP, but reject all non-socketio connections to it. In fact, that's how some of my applications work. I have some cross-domain issues with it, but it can be the way to do it.
